In [1]:
import pandas as pd

df = pd.read_csv("deliveries.csv")
print(df.head())

   match_id  inning           batting_team                 bowling_team  over  \
0    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0
1    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0
2    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0
3    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0
4    335982       1  Kolkata Knight Riders  Royal Challengers Bangalore     0

   ball       batter   bowler  non_striker  batsman_runs  extra_runs  \
0     1   SC Ganguly  P Kumar  BB McCullum             0           1
1     2  BB McCullum  P Kumar   SC Ganguly             0           0
2     3  BB McCullum  P Kumar   SC Ganguly             0           1
3     4  BB McCullum  P Kumar   SC Ganguly             0           0
4     5  BB McCullum  P Kumar   SC Ganguly             0           0

   total_runs extras_type  is_wicket player_dismissed dismissal_kind fielder
0           1     legbyes          0              NaN            NaN     NaN
1           0         NaN          0              NaN            NaN     NaN
2           1       wides          0              NaN            NaN     NaN
3           0         NaN          0              NaN            NaN     NaN
4           0         NaN          0              NaN            NaN     NaN

In [4]:

pd.read_csv(
    "deliveries.csv",
    sep=",",
    header=0,
    index_col=0,
    na_values=["NA"],
)

,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
match_id,,,,,,,,,,,,,,,,
335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [5]:
print("Deliveries shape:", df.shape)

Deliveries shape: (260920, 17)

In [6]:

print("Deliveries columns:")
print(df.columns)

Deliveries columns:
Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [7]:

print("Deliveries data types:")
print(df.dtypes)

Deliveries data types:
match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed      str
dismissal_kind        str
fielder               str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

In [9]:
print(df.isna().sum())

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [10]:
deliveries = df.dropna(subset=["match_id", "total_runs"])

In [11]:
deliveries["extra_runs"] = deliveries["extra_runs"].fillna(0)

In [12]:
deliveries_ids = set(deliveries["match_id"])

In [13]:
deliveries_clean = deliveries.copy()

deliveries_clean["extras_type"] = deliveries_clean["extras_type"].fillna("None")
deliveries_clean["dismissal_kind"] = deliveries_clean["dismissal_kind"].fillna("Not Out")
deliveries_clean["player_dismissed"] = deliveries_clean["player_dismissed"].fillna("None")
deliveries_clean["fielder"] = deliveries_clean["fielder"].fillna("None")

In [ ]:
invalid_wickets = deliveries_clean[
    (deliveries_clean["is_wicket"] == 0) &
    (deliveries_clean["dismissal_kind"] != "Not Out")
]

print("Invalid wicket rows:", len(invalid_wickets))

Invalid wicket rows: 0

In [ ]:
numeric_cols = [
    "inning", "over", "ball", "batsman_runs",
    "extra_runs", "total_runs", "is_wicket"
]

deliveries_clean[numeric_cols] = deliveries_clean[numeric_cols].apply(
    pd.to_numeric, errors="coerce"
)

categorical_cols = [
    "batting_team", "bowling_team",
    "batter", "bowler", "non_striker",
    "extras_type", "dismissal_kind", "fielder"
]

for col in categorical_cols:
    deliveries_clean[col] = deliveries_clean[col].astype("category")

In [16]:
deliveries_clean.isna().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [17]:
deliveries_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  category
 3   bowling_team      260920 non-null  category
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  category
 7   bowler            260920 non-null  category
 8   non_striker       260920 non-null  category
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       260920 non-null  category
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  260920 non-null  str
 15  dismissal_kind    260920 non-null  category
 16  fielder           260920 non-null  category
dtypes: category(8), int64(8), str(1)
memory usage: 20.9 MB

In [19]:
def standardize_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

deliveries_df = standardize_columns(deliveries_clean)

In [20]:
deliveries_df["computed_total_runs"] = (
    deliveries_df["batsman_runs"] + deliveries_df["extra_runs"]
)

In [21]:
(deliveries_df["computed_total_runs"] == deliveries_df["total_runs"]).all()

np.True_

In [ ]:

deliveries_df["over_ball"] = (
    deliveries_df["over"].astype(str) + "." +
    deliveries_df["ball"].astype(str)
)


deliveries_df["is_wicket"] = deliveries_df["is_wicket"].astype(bool)


deliveries_df["is_legal_delivery"] = deliveries_df["extras_type"].isin(
    ["wide", "no ball"]
) == False

In [28]:
matches = pd.read_csv("matches.csv")

In [29]:

print("Missing values in matches:")
print(matches.isna().sum())

Missing values in matches:
id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [30]:
matches["winner"] = matches["winner"].fillna("No Result")

In [31]:
matches_ids = set(matches["id"])

In [33]:

missing_in_matches = deliveries_ids - matches_ids
print("Match IDs in deliveries but not in matches:", missing_in_matches)
matches_clean = matches.copy()

Match IDs in deliveries but not in matches: set()

In [35]:
matches_clean = matches.copy()

matches_clean["city"] = matches_clean["city"].fillna("Unknown")
matches_clean["player_of_match"] = matches_clean["player_of_match"].fillna("No Award")
matches_clean["winner"] = matches_clean["winner"].fillna("No Result")
matches_clean["result_margin"] = matches_clean["result_margin"].fillna(0)
matches_clean["target_runs"] = matches_clean["target_runs"].fillna(0)
matches_clean["target_overs"] = matches_clean["target_overs"].fillna(0)
matches_clean["method"] = matches_clean["method"].fillna("Normal")

In [36]:
matches_clean.isna().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [37]:
matches_df = standardize_columns(matches_clean)

In [38]:

unified_df = deliveries_df.merge(
    matches_df,
    left_on="match_id",
    right_on="id",
    how="inner"
)

In [39]:
print("Unified shape:", unified_df.shape)
unified_df.info()

Unified shape: (260920, 40)
<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 40 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   match_id             260920 non-null  int64
 1   inning               260920 non-null  int64
 2   batting_team         260920 non-null  category
 3   bowling_team         260920 non-null  category
 4   over                 260920 non-null  int64
 5   ball                 260920 non-null  int64
 6   batter               260920 non-null  category
 7   bowler               260920 non-null  category
 8   non_striker          260920 non-null  category
 9   batsman_runs         260920 non-null  int64
 10  extra_runs           260920 non-null  int64
 11  total_runs           260920 non-null  int64
 12  extras_type          260920 non-null  category
 13  is_wicket            260920 non-null  bool
 14  player_dismissed     260920 non-null  str
 15  dismissal_kind       260920 non-null  category
 16  fielder              260920 non-null  category
 17  computed_total_runs  260920 non-null  int64
 18  over_ball            260920 non-null  str
 19  is_legal_delivery    260920 non-null  bool
 20  id                   260920 non-null  int64
 21  season               260920 non-null  str
 22  city                 260920 non-null  str
 23  date                 260920 non-null  str
 24  match_type           260920 non-null  str
 25  player_of_match      260920 non-null  str
 26  venue                260920 non-null  str
 27  team1                260920 non-null  str
 28  team2                260920 non-null  str
 29  toss_winner          260920 non-null  str
 30  toss_decision        260920 non-null  str
 31  winner               260920 non-null  str
 32  result               260920 non-null  str
 33  result_margin        260920 non-null  float64
 34  target_runs          260920 non-null  float64
 35  target_overs         260920 non-null  float64
 36  super_over           260920 non-null  str
 37  method               260920 non-null  str
 38  umpire1              260920 non-null  str
 39  umpire2              260920 non-null  str
dtypes: bool(2), category(8), float64(3), int64(9), str(18)
memory usage: 63.2 MB

In [40]:
required_columns = [
    "match_id", "season", "venue",
    "batting_team", "bowling_team",
    "batter", "bowler",
    "total_runs", "computed_total_runs"
]

missing = set(required_columns) - set(unified_df.columns)
print("Missing columns:", missing)

Missing columns: set()

In [41]:
unified_df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,Normal,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,Normal,J Madanagopal,Nitin Menon
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,Normal,J Madanagopal,Nitin Menon
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,Normal,J Madanagopal,Nitin Menon
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,Normal,J Madanagopal,Nitin Menon
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,Normal,J Madanagopal,Nitin Menon

In [42]:
runs_per_match = (
    unified_df
    .groupby("match_id")["total_runs"]
    .sum()
    .reset_index(name="total_runs")
)

In [43]:
runs_team_match = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
)

In [44]:
top_10_batters = (
    unified_df
    .groupby("batter")["batsman_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

In [45]:
batting_stats = (
    unified_df
    .groupby("batter")
    .agg(
        runs=("batsman_runs", "sum"),
        balls=("ball", "count")
    )
    .reset_index()
)

batting_stats["strike_rate"] = (
    batting_stats["runs"] / batting_stats["balls"] * 100
)

In [46]:
bowling_stats = (
    unified_df
    .groupby("bowler")
    .agg(
        runs_conceded=("total_runs", "sum"),
        balls=("ball", "count")
    )
    .reset_index()
)

bowling_stats["overs"] = bowling_stats["balls"] / 6
bowling_stats["economy"] = bowling_stats["runs_conceded"] / bowling_stats["overs"]

top_10_economy = bowling_stats.sort_values("economy").head(10)

In [47]:
batter_match_runs = (
    unified_df
    .groupby(["match_id", "batter"])["batsman_runs"]
    .sum()
    .reset_index()
)

consistency = (
    batter_match_runs
    .groupby("batter")
    .agg(
        avg_runs=("batsman_runs", "mean"),
        matches=("match_id", "nunique")
    )
    .reset_index()
)

consistent_batters = (
    consistency[consistency["matches"] >= 20]
    .sort_values("avg_runs", ascending=False)
)

In [48]:
highest_score = (
    batter_match_runs
    .sort_values("batsman_runs", ascending=False)
    .head(1)
)

In [49]:
total_fours = (unified_df["batsman_runs"] == 4).sum()
total_sixes = (unified_df["batsman_runs"] == 6).sum()

In [50]:
boundary_stats = (
    unified_df
    .assign(
        fours=unified_df["batsman_runs"] == 4,
        sixes=unified_df["batsman_runs"] == 6
    )
    .groupby("batter")[["fours", "sixes"]]
    .sum()
    .sort_values(["sixes", "fours"], ascending=False)
)

In [51]:
boundary_runs = (
    unified_df
    .assign(boundary_runs=lambda x:
            x["batsman_runs"].where(x["batsman_runs"].isin([4, 6]), 0))
    .groupby("batter")
    .agg(
        total_runs=("batsman_runs", "sum"),
        boundary_runs=("boundary_runs", "sum")
    )
    .reset_index()
)

boundary_runs["boundary_percentage"] = (
    boundary_runs["boundary_runs"] /
    boundary_runs["total_runs"] * 100
)

In [52]:
dot_balls = unified_df[unified_df["total_runs"] == 0]

In [53]:
top_dot_bowlers = (
    dot_balls
    .groupby("bowler")
    .size()
    .sort_values(ascending=False)
)

In [54]:
runs_per_over = (
    unified_df
    .groupby("over")["total_runs"]
    .mean()
    .reset_index(name="avg_runs")
)

In [55]:
runs_per_over.sort_values("avg_runs", ascending=False)

    over  avg_runs
19    19  1.776855
18    18  1.646896
17    17  1.587839
16    16  1.498778
15    15  1.434273
14    14  1.393504
5      5  1.373055
4      4  1.369100
3      3  1.356538
13    13  1.343645
2      2  1.316099
12    12  1.301240
11    11  1.287686
10    10  1.262623
8      8  1.242087
9      9  1.224577
7      7  1.189948
1      1  1.173528
6      6  1.103107
0      0  0.981663

In [56]:
powerplay = unified_df[unified_df["over"] <= 6]

powerplay_team_runs = (
    powerplay
    .groupby("batting_team")["total_runs"]
    .sum()
    .sort_values(ascending=False)
)

In [57]:
death_overs = unified_df[unified_df["over"] >= 16]

death_team_runs = (
    death_overs
    .groupby("batting_team")["total_runs"]
    .sum()
    .sort_values(ascending=False)
)

death_batter_runs = (
    death_overs
    .groupby("batter")["batsman_runs"]
    .sum()
    .sort_values(ascending=False)
)

In [58]:
inning_runs = (
    unified_df
    .groupby("inning")["total_runs"]
    .mean()
    .reset_index()
)

In [60]:
toss_runs = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
    .merge(
        unified_df[["match_id", "toss_winner"]].drop_duplicates(),
        on="match_id"
    )
)

toss_runs["is_toss_winner"] = (
    toss_runs["batting_team"] == toss_runs["toss_winner"]
)

toss_impact = toss_runs.groupby("is_toss_winner")["total_runs"].mean()

In [61]:
pom_runs = (
    unified_df
    .groupby(["match_id", "batter"])["batsman_runs"]
    .sum()
    .reset_index()
    .merge(
        unified_df[["match_id", "player_of_match"]].drop_duplicates(),
        on="match_id"
    )
)

pom_performance = pom_runs[
    pom_runs["batter"] == pom_runs["player_of_match"]
]

In [62]:
venue_stats = (
    unified_df
    .groupby("venue")
    .agg(
        matches=("match_id", "nunique"),
        avg_runs=("total_runs", "mean")
    )
    .reset_index()
)

In [63]:
city_runs = (
    unified_df
    .groupby("city")["total_runs"]
    .mean()
    .sort_values(ascending=False)
)

In [64]:
season_runs = (
    unified_df
    .groupby("season")["total_runs"]
    .sum()
    .reset_index()
)

In [65]:
match_runs = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
)

predicted_winner = (
    match_runs
    .sort_values(["match_id", "total_runs"], ascending=[True, False])
    .drop_duplicates("match_id")
)

winner_check = predicted_winner.merge(
    unified_df[["match_id", "winner"]].drop_duplicates(),
    on="match_id"
)

winner_check["correct_prediction"] = (
    winner_check["batting_team"] == winner_check["winner"]
)

In [67]:
import pandas as pd

# Helper function for clean display
def section(title):
    print(title.upper())

# 1. Total Runs per Match
section("1. Total Runs per Match")
runs_per_match = unified_df.groupby("match_id")["total_runs"].sum()
display(runs_per_match.head())


# 2. Runs per Team per Match
section("2. Runs per Team per Match")
runs_team_match = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
)
display(runs_team_match.head())


# 3. Top 10 Batters
section("3. Top 10 Batters by Total Runs")
top_10_batters = (
    unified_df
    .groupby("batter")["batsman_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
display(top_10_batters)


# 4. Strike Rate of Batters
section("4. Strike Rate of Batters")
strike_rate = (
    unified_df
    .groupby("batter")
    .agg(
        runs=("batsman_runs", "sum"),
        balls=("ball", "count")
    )
)
strike_rate["strike_rate"] = (strike_rate["runs"] / strike_rate["balls"]) * 100
display(strike_rate.sort_values("strike_rate", ascending=False).head(10))


# 5. Top 10 Bowlers by Economy
section("5. Top 10 Bowlers by Economy")
bowling = (
    unified_df
    .groupby("bowler")
    .agg(
        runs_conceded=("total_runs", "sum"),
        balls=("ball", "count")
    )
)
bowling["overs"] = bowling["balls"] / 6
bowling["economy"] = bowling["runs_conceded"] / bowling["overs"]
display(bowling.sort_values("economy").head(10))


# 6. Most Consistent Batters
section("6. Most Consistent Batters")
batter_match_runs = (
    unified_df
    .groupby(["match_id", "batter"])["batsman_runs"]
    .sum()
    .reset_index()
)

consistent = (
    batter_match_runs
    .groupby("batter")
    .agg(
        avg_runs=("batsman_runs", "mean"),
        matches=("match_id", "nunique")
    )
)

display(
    consistent[consistent["matches"] >= 20]
    .sort_values("avg_runs", ascending=False)
    .head(10)
)


# 7. Highest Individual Score in a Match
section("7. Highest Individual Score in a Match")
display(batter_match_runs.sort_values("batsman_runs", ascending=False).head(1))


# 8. Boundary Analysis
section("8. Boundary Analysis")
total_fours = (unified_df["batsman_runs"] == 4).sum()
total_sixes = (unified_df["batsman_runs"] == 6).sum()
print(f"Total Fours: {total_fours}")
print(f"Total Sixes: {total_sixes}")

boundary_players = (
    unified_df
    .assign(
        fours=unified_df["batsman_runs"] == 4,
        sixes=unified_df["batsman_runs"] == 6
    )
    .groupby("batter")[["fours", "sixes"]]
    .sum()
    .sort_values(["sixes", "fours"], ascending=False)
)
display(boundary_players.head(10))


# 9. Boundary Percentage
section("9. Boundary Percentage per Batter")
boundary_pct = (
    unified_df
    .assign(boundary_runs=lambda x: x["batsman_runs"].where(x["batsman_runs"].isin([4, 6]), 0))
    .groupby("batter")
    .agg(
        total_runs=("batsman_runs", "sum"),
        boundary_runs=("boundary_runs", "sum")
    )
)
boundary_pct["boundary_percentage"] = (
    boundary_pct["boundary_runs"] / boundary_pct["total_runs"] * 100
)
display(boundary_pct.sort_values("boundary_percentage", ascending=False).head(10))


# 10. Dot Ball Analysis
section("10. Dot Ball Analysis")
dot_balls = unified_df[unified_df["total_runs"] == 0]
top_dot_bowlers = dot_balls.groupby("bowler").size().sort_values(ascending=False)
display(top_dot_bowlers.head(10))


# 11. Runs per Over Analysis
section("11. Runs per Over Analysis")
runs_per_over = unified_df.groupby("over")["total_runs"].mean()
display(runs_per_over)


# 12. Powerplay Performance (Overs 1–6)
section("12. Powerplay Performance")
powerplay = unified_df[unified_df["over"] <= 6]
display(
    powerplay.groupby("batting_team")["total_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)


# 13. Death Overs Performance (Overs 16–20)
section("13. Death Overs Performance")
death = unified_df[unified_df["over"] >= 16]

display(
    death.groupby("batting_team")["total_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

display(
    death.groupby("batter")["batsman_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)


# 14. Run Distribution per Inning
section("14. Run Distribution per Inning")
display(
    unified_df.groupby("inning")["total_runs"]
    .mean()
)


# 15. Toss Impact Analysis
section("15. Toss Impact Analysis")
toss_runs = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
    .merge(
        unified_df[["match_id", "toss_winner"]].drop_duplicates(),
        on="match_id"
    )
)

toss_runs["is_toss_winner"] = toss_runs["batting_team"] == toss_runs["toss_winner"]
display(toss_runs.groupby("is_toss_winner")["total_runs"].mean())


# 16. Player of Match Contribution
section("16. Player of Match Contribution")
pom = (
    batter_match_runs
    .merge(
        unified_df[["match_id", "player_of_match"]].drop_duplicates(),
        on="match_id"
    )
)

display(pom[pom["batter"] == pom["player_of_match"]].head())


# 17. Venue-wise Analysis
section("17. Venue-wise Analysis")
venue_stats = (
    unified_df
    .groupby("venue")
    .agg(
        matches=("match_id", "nunique"),
        avg_runs=("total_runs", "mean")
    )
)
display(venue_stats.sort_values("avg_runs", ascending=False).head(10))


# 18. City-wise Scoring Trends
section("18. City-wise Scoring Trends")
display(
    unified_df.groupby("city")["total_runs"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)


# 19. Season-wise Run Trends
section("19. Season-wise Run Trends")
display(
    unified_df.groupby("season")["total_runs"]
    .sum()
    .reset_index()
)


# 20. Winning Team Analysis
section("20. Winning Team Analysis")
match_runs = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
)

predicted = (
    match_runs
    .sort_values(["match_id", "total_runs"], ascending=[True, False])
    .drop_duplicates("match_id")
)

winner_check = predicted.merge(
    unified_df[["match_id", "winner"]].drop_duplicates(),
    on="match_id"
)

winner_check["prediction_correct"] = (
    winner_check["batting_team"] == winner_check["winner"]
)

display(winner_check.head())

1. TOTAL RUNS PER MATCH

match_id
335982    304
335983    447
335984    261
335985    331
335986    222
Name: total_runs, dtype: int64

2. RUNS PER TEAM PER MATCH

   match_id                 batting_team  total_runs
0    335982        Kolkata Knight Riders         222
1    335982  Royal Challengers Bangalore          82
2    335983          Chennai Super Kings         240
3    335983              Kings XI Punjab         207
4    335984             Delhi Daredevils         132

3. TOP 10 BATTERS BY TOTAL RUNS

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

4. STRIKE RATE OF BATTERS

                 runs  balls  strike_rate
batter
L Wood              9      3   300.000000
B Stanlake          5      2   250.000000
J Fraser-McGurk   330    150   220.000000
R Sai Kishore      13      6   216.666667
Umar Gul           39     19   205.263158
RS Sodhi            4      2   200.000000
Shahid Afridi      81     46   176.086957
I Malhotra          7      4   175.000000
WG Jacks          230    133   172.932331
PD Salt           653    385   169.610390

5. TOP 10 BOWLERS BY ECONOMY

               runs_conceded  balls     overs   economy
bowler
AC Gilchrist               0      1  0.166667  0.000000
R Ravindra                 7     12  2.000000  3.500000
NB Singh                  18     25  4.166667  4.320000
Sachin Baby                8     10  1.666667  4.800000
AM Rahane                  5      6  1.000000  5.000000
LA Carseldine              6      7  1.166667  5.142857
SS Mundhe                  6      7  1.166667  5.142857
DJ Thornely               40     44  7.333333  5.454545
M Manhas                  42     42  7.000000  6.000000
MW Short                  25     25  4.166667  6.000000

6. MOST CONSISTENT BATTERS

                  avg_runs  matches
batter
DP Conway        42.000000       22
B Sai Sudharsan  41.360000       25
KL Rahul         38.434426      122
LMP Simmons      37.206897       29
RD Gaikwad       36.615385       65
SE Marsh         36.072464       69
DA Warner        35.690217      184
CH Gayle         35.439716      141
ML Hayden        34.593750       32
MEK Hussey       34.086207       58

7. HIGHEST INDIVIDUAL SCORE IN A MATCH

      match_id    batter  batsman_runs
5302    598027  CH Gayle           175

8. BOUNDARY ANALYSIS
Total Fours: 29850
Total Sixes: 13051

                fours  sixes
batter
CH Gayle          408    359
RG Sharma         599    281
V Kohli           708    273
AB de Villiers    414    253
MS Dhoni          363    252
DA Warner         663    236
KA Pollard        221    224
AD Russell        171    209
SV Samson         352    206
SK Raina          506    204

9. BOUNDARY PERCENTAGE PER BATTER

                 total_runs  boundary_runs  boundary_percentage
batter
VRV Singh                 4              4           100.000000
BA Bhatt                  6              6           100.000000
RS Sodhi                  4              4           100.000000
Liton Das                 4              4           100.000000
A Tomar                   4              4           100.000000
P Chopra                  8              8           100.000000
GD McGrath                4              4           100.000000
R Sai Kishore            13             12            92.307692
J Fraser-McGurk         330            296            89.696970
AA Kulkarni               9              8            88.888889

10. DOT BALL ANALYSIS

bowler
B Kumar            1632
SP Narine          1569
R Ashwin           1552
PP Chawla          1325
Harbhajan Singh    1263
JJ Bumrah          1228
RA Jadeja          1216
YS Chahal          1194
UT Yadav           1186
A Mishra           1185
dtype: int64

11. RUNS PER OVER ANALYSIS

over
0     0.981663
1     1.173528
2     1.316099
3     1.356538
4     1.369100
5     1.373055
6     1.103107
7     1.189948
8     1.242087
9     1.224577
10    1.262623
11    1.287686
12    1.301240
13    1.343645
14    1.393504
15    1.434273
16    1.498778
17    1.587839
18    1.646896
19    1.776855
Name: total_runs, dtype: float64

12. POWERPLAY PERFORMANCE

batting_team
Mumbai Indians                 13943
Kolkata Knight Riders          13632
Chennai Super Kings            12631
Royal Challengers Bangalore    12429
Rajasthan Royals               11774
Kings XI Punjab                10295
Sunrisers Hyderabad            10170
Delhi Daredevils                8503
Delhi Capitals                  5358
Deccan Chargers                 3889
Name: total_runs, dtype: int64

13. DEATH OVERS PERFORMANCE

batting_team
Mumbai Indians                 9598
Chennai Super Kings            9061
Royal Challengers Bangalore    8417
Kolkata Knight Riders          8053
Rajasthan Royals               7281
Sunrisers Hyderabad            6237
Kings XI Punjab                6227
Delhi Daredevils               5043
Delhi Capitals                 3141
Deccan Chargers                2539
Name: total_runs, dtype: int64

batter
MS Dhoni          2786
KA Pollard        1708
KD Karthik        1565
AB de Villiers    1421
RA Jadeja         1420
RG Sharma         1176
HH Pandya         1126
V Kohli           1099
AD Russell        1065
DA Miller          988
Name: batsman_runs, dtype: int64

14. RUN DISTRIBUTION PER INNING

inning
1    1.342591
2    1.321733
3    1.779221
4    1.708333
5    1.375000
6    3.750000
Name: total_runs, dtype: float64

15. TOSS IMPACT ANALYSIS

is_toss_winner
False    161.351920
True     156.666972
Name: total_runs, dtype: float64

16. PLAYER OF MATCH CONTRIBUTION

    match_id       batter  batsman_runs player_of_match
2     335982  BB McCullum           158     BB McCullum
21    335983   MEK Hussey           116      MEK Hussey
49    335985   MV Boucher            39      MV Boucher
61    335986    DJ Hussey            38       DJ Hussey
86    335987    SR Watson            76       SR Watson

17. VENUE-WISE ANALYSIS

                                                    matches  avg_runs
venue
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...        2  1.600000
Eden Gardens, Kolkata                                    16  1.577242
M Chinnaswamy Stadium, Bengaluru                         14  1.554777
Himachal Pradesh Cricket Association Stadium, D...        4  1.542770
Punjab Cricket Association IS Bindra Stadium, M...        5  1.537697
Arun Jaitley Stadium, Delhi                              16  1.536967
Rajiv Gandhi International Stadium, Uppal, Hyde...       13  1.509548
M.Chinnaswamy Stadium                                    15  1.467373
Holkar Cricket Stadium                                    9  1.461578
Sawai Mansingh Stadium, Jaipur                           10  1.443460

18. CITY-WISE SCORING TRENDS

city
Bengaluru     1.510626
Indore        1.461578
Kanpur        1.409338
Dharamsala    1.404648
Rajkot        1.399832
Ahmedabad     1.393312
Guwahati      1.378890
Chandigarh    1.372202
Delhi         1.366073
Kolkata       1.361485
Name: total_runs, dtype: float64

19. SEASON-WISE RUN TRENDS

     season  total_runs
0   2007/08       17937
1      2009       16353
2   2009/10       18883
3      2011       21154
4      2012       22453
5      2013       22602
6      2014       18931
7      2015       18353
8      2016       18862
9      2017       18786
10     2018       19901
11     2019       19434
12  2020/21       19416
13     2021       18637
14     2022       24395
15     2023       25688
16     2024       25971

20. WINNING TEAM ANALYSIS

,match_id,batting_team,total_runs,winner,prediction_correct
0,335982,Kolkata Knight Riders,222,Kolkata Knight Riders,True
1,335983,Chennai Super Kings,240,Chennai Super Kings,True
2,335984,Delhi Daredevils,132,Delhi Daredevils,True
3,335985,Royal Challengers Bangalore,166,Royal Challengers Bangalore,True
4,335986,Kolkata Knight Riders,112,Kolkata Knight Riders,True

In [68]:
# Runs per batter per match
batter_match_runs = (
    unified_df
    .groupby(["match_id", "batter"])["batsman_runs"]
    .sum()
    .reset_index()
)

# Consistency calculation
consistent_batters = (
    batter_match_runs
    .groupby("batter")
    .agg(
        avg_runs_per_match=("batsman_runs", "mean"),
        matches_played=("match_id", "nunique")
    )
    .reset_index()
)

# Apply minimum match filter
most_consistent_batter = (
    consistent_batters[consistent_batters["matches_played"] >= 20]
    .sort_values("avg_runs_per_match", ascending=False)
    .head(1)
)

print("Most Consistent Batter:")
print(most_consistent_batter)

Most Consistent Batter:
        batter  avg_runs_per_match  matches_played
170  DP Conway                42.0              22

In [69]:
death_overs = unified_df[unified_df["over"] >= 16]

best_death_team = (
    death_overs
    .groupby("batting_team")["total_runs"]
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

print("\nBest Death‑Over Team:")
print(best_death_team)

Best Death‑Over Team:
batting_team
Mumbai Indians    9598
Name: total_runs, dtype: int64

In [70]:
venue_scoring = (
    unified_df
    .groupby("venue")["total_runs"]
    .mean()
    .reset_index(name="avg_runs_per_ball")
    .sort_values("avg_runs_per_ball", ascending=False)
)

high_scoring_venues = venue_scoring.head(5)

print("\nHigh‑Scoring Venues:")
print(high_scoring_venues)

High‑Scoring Venues:
                                                venue  avg_runs_per_ball
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...           1.600000
15                              Eden Gardens, Kolkata           1.577242
24                   M Chinnaswamy Stadium, Bengaluru           1.554777
19  Himachal Pradesh Cricket Association Stadium, ...           1.542770
39  Punjab Cricket Association IS Bindra Stadium, ...           1.537697

In [71]:
def snake_case(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df


def readable_columns(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.replace("_", " ")
        .str.title()
    )
    return df

In [72]:
report_runs_per_match = (
    unified_df
    .groupby("match_id")["total_runs"]
    .sum()
    .reset_index()
    .rename(columns={"total_runs": "total_runs_scored"})
    .sort_values("total_runs_scored", ascending=False)
)

report_runs_per_match = readable_columns(report_runs_per_match)
display(report_runs_per_match.head(10))

      Match Id  Total Runs Scored
1053   1426268                549
1031   1422126                523
1065   1426280                523
1066   1426281                504
146     419137                469
1058   1426273                465
679    1136604                459
987    1359512                458
626    1082641                453
791    1216527                449

In [73]:
report_team_match_runs = (
    unified_df
    .groupby(["match_id", "batting_team"])["total_runs"]
    .sum()
    .reset_index()
    .rename(columns={
        "batting_team": "team",
        "total_runs": "runs_scored"
    })
    .sort_values(["match_id", "runs_scored"], ascending=[True, False])
)

report_team_match_runs = readable_columns(report_team_match_runs)
display(report_team_match_runs.head(10))

   Match Id                         Team  Runs Scored
0    335982        Kolkata Knight Riders          222
1    335982  Royal Challengers Bangalore           82
2    335983          Chennai Super Kings          240
3    335983              Kings XI Punjab          207
4    335984             Delhi Daredevils          132
5    335984             Rajasthan Royals          129
7    335985  Royal Challengers Bangalore          166
6    335985               Mumbai Indians          165
9    335986        Kolkata Knight Riders          112
8    335986              Deccan Chargers          110

In [74]:
report_top_batters = (
    unified_df
    .groupby("batter")["batsman_runs"]
    .sum()
    .reset_index()
    .rename(columns={
        "batter": "player",
        "batsman_runs": "total_runs"
    })
    .sort_values("total_runs", ascending=False)
    .head(10)
)

report_top_batters = readable_columns(report_top_batters)
display(report_top_batters)

             Player  Total Runs
631         V Kohli        8014
512        S Dhawan        6769
477       RG Sharma        6630
147       DA Warner        6567
546        SK Raina        5536
374        MS Dhoni        5243
30   AB de Villiers        5181
124        CH Gayle        4997
501      RV Uthappa        4954
282      KD Karthik        4843

In [75]:
report_strike_rate = (
    unified_df
    .groupby("batter")
    .agg(
        runs=("batsman_runs", "sum"),
        balls=("ball", "count")
    )
    .reset_index()
)

report_strike_rate["strike_rate"] = (
    report_strike_rate["runs"] / report_strike_rate["balls"] * 100
)

report_strike_rate = (
    report_strike_rate
    .rename(columns={"batter": "player"})
    .sort_values("strike_rate", ascending=False)
)

report_strike_rate = readable_columns(report_strike_rate)
display(report_strike_rate.head(10))

              Player  Runs  Balls  Strike Rate
312           L Wood     9      3   300.000000
97        B Stanlake     5      2   250.000000
234  J Fraser-McGurk   330    150   220.000000
461    R Sai Kishore    13      6   216.666667
629         Umar Gul    39     19   205.263158
497         RS Sodhi     4      2   200.000000
583    Shahid Afridi    81     46   176.086957
222       I Malhotra     7      4   175.000000
652         WG Jacks   230    133   172.932331
433          PD Salt   653    385   169.610390

In [76]:
report_bowling = (
    unified_df
    .groupby("bowler")
    .agg(
        runs_conceded=("total_runs", "sum"),
        balls=("ball", "count")
    )
    .reset_index()
)

report_bowling["overs"] = report_bowling["balls"] / 6
report_bowling["economy"] = (
    report_bowling["runs_conceded"] / report_bowling["overs"]
)

report_bowling = (
    report_bowling
    .rename(columns={"bowler": "player"})
    .sort_values("economy")
)

report_bowling = readable_columns(report_bowling)
display(report_bowling.head(10))

            Player  Runs Conceded  Balls     Overs   Economy
24    AC Gilchrist              0      1  0.166667  0.000000
364     R Ravindra              7     12  2.000000  3.500000
317       NB Singh             18     25  4.166667  4.320000
460    Sachin Baby              8     10  1.666667  4.800000
38       AM Rahane              5      6  1.000000  5.000000
245  LA Carseldine              6      7  1.166667  5.142857
453      SS Mundhe              6      7  1.166667  5.142857
125    DJ Thornely             40     44  7.333333  5.454545
260       M Manhas             42     42  7.000000  6.000000
296       MW Short             25     25  4.166667  6.000000

In [77]:
batter_match_runs = (
    unified_df
    .groupby(["match_id", "batter"])["batsman_runs"]
    .sum()
    .reset_index()
)

report_consistency = (
    batter_match_runs
    .groupby("batter")
    .agg(
        avg_runs_per_match=("batsman_runs", "mean"),
        matches_played=("match_id", "nunique")
    )
    .reset_index()
)

report_consistency = (
    report_consistency
    .rename(columns={"batter": "player"})
    .sort_values("avg_runs_per_match", ascending=False)
)

report_consistency = readable_columns(report_consistency)
display(report_consistency.head(10))

              Player  Avg Runs Per Match  Matches Played
648   Vivrant Sharma           69.000000               1
170        DP Conway           42.000000              22
96   B Sai Sudharsan           41.360000              25
289         KL Rahul           38.434426             122
319      LMP Simmons           37.206897              29
234  J Fraser-McGurk           36.666667               9
473       RD Gaikwad           36.615385              65
542         SE Marsh           36.072464              69
214          HM Amla           36.062500              16
147        DA Warner           35.690217             184

In [78]:
report_venues = (
    unified_df
    .groupby("venue")
    .agg(
        matches=("match_id", "nunique"),
        avg_runs_per_ball=("total_runs", "mean")
    )
    .reset_index()
    .sort_values("avg_runs_per_ball", ascending=False)
)

report_venues = readable_columns(report_venues)
display(report_venues.head(10))

,Venue,Matches,Avg Runs Per Ball
12,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,2,1.600000
15,"Eden Gardens, Kolkata",16,1.577242
24,"M Chinnaswamy Stadium, Bengaluru",14,1.554777
19,"Himachal Pradesh Cricket Association Stadium, ...",4,1.542770
39,"Punjab Cricket Association IS Bindra Stadium, ...",5,1.537697
1,"Arun Jaitley Stadium, Delhi",16,1.536967
43,"Rajiv Gandhi International Stadium, Uppal, Hyd...",13,1.509548
25,M.Chinnaswamy Stadium,15,1.467373
20,Holkar Cricket Stadium,9,1.461578
47,"Sawai Mansingh Stadium, Jaipur",10,1.443460

In [85]:
import os

output_dir = "output"
os.makedirs(output_dir, exist_ok=True)

In [80]:
report_runs_per_match.to_csv(
    "output/runs_per_match.csv", index=False
)

report_top_batters.to_csv(
    "output/top_batters.csv", index=False
)

report_strike_rate.to_csv(
    "output/strike_rate.csv", index=False
)

report_bowling.to_csv(
    "output/economy.csv", index=False
)

report_team_match_runs.to_csv(
    "output/team_scores.csv", index=False
)

death_team_runs.reset_index().to_csv(
    "output/death_overs.csv", index=False
)

In [84]:
with pd.ExcelWriter("ipl_analysis.xlsx", engine="xlsxwriter") as writer:

    report_runs_per_match.to_excel(
        writer,
        sheet_name="Runs per Match",
        index=False
    )

    report_top_batters.to_excel(
        writer,
        sheet_name="Top Batters",
        index=False
    )

    report_strike_rate.to_excel(
        writer,
        sheet_name="Strike Rate",
        index=False
    )

    report_bowling.to_excel(
        writer,
        sheet_name="Bowling Economy",
        index=False
    )

    report_team_match_runs.to_excel(
        writer,
        sheet_name="Team Scores",
        index=False
    )

    death_team_runs.reset_index().to_excel(
        writer,
        sheet_name="Death Overs",
        index=False
    )

ModuleNotFoundError: No module named 'xlsxwriter'